version: '3'
services:
  db1:
    image: postgres:9.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: db1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db1
    volumes:
        - ./db1/:/var/lib/postgresql/data

  db2:
    image: postgres:9.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: db2
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db2
    volumes:
        - ./db2/:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
